# Generated by Django 4.2.3 on 2024-07-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_dictionary_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErfanDictionary",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_app.dictionary",),
        ),
        migrations.CreateModel(
            name="MasoudDictionary",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_app.dictionary",),
        ),
    ]
